services:
  - type: web
    name: whatsapp-lead-server
    env: node
    plan: free
    buildCommand: npm install && npx puppeteer install chrome
    startCommand: node server.js
    autoDeploy: true

    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"